### ISSUE TITLE
Set the homepage URL in the metadata of this repository

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/CddInterface#11]
At the top of the page https://github.com/homalg-project/CddInterface there is a description "Gap Interface to Cdd" -- next to it could and IMHO should appear a link to the homepage of this project, as depicted here: https://stackoverflow.com/a/21649064

**Comment by fingolfin** [comment]
Same of course for NConvex

**Comment by kamalsaleh** [comment]
Done!. Thank you for the suggestions.
