### ISSUE TITLE
Errors when loading CddInterface

### ISSUE THREAD

**Issue by lmyreg2017** [homalg-project/CddInterface#14]
![Screenshot from 2019-10-14 15-59-53](https://user-images.githubusercontent.com/33969980/66894065-84f4bd80-efbd-11e9-8d08-a2fc85f7abfb.png)

Dear developer,

Sorry to bother you with this error I encountered when loading CddInterface package, may I ask this error is related to not compiling successfully or other mistake I made?

**Comment by kamalsaleh** [comment]
Hello and thank you for reporting this. The dynamic file CddInterface.so should be created if compiling the package was successful. So, since it is not found, there should be some error when running the script ./install.sh.
After running the script ./install.sh successfully you should see something like this
```
CC       src/CddInterface_la-CddInterface.lo
CCLD     CddInterface.la
/bin/mkdir -p ./bin/x86_64-pc-linux-gnu-default64-kv3
cp .libs/CddInterface.so /home/kamal/Documents/local_gap_packages/pkg/CddInterface/bin/x86_64-pc-linux-gnu-default64-kv3/CddInterface.so
SUCCESS!
```
Can you please tell me the output you see after running "./install.sh" ? 
Maybe you need root permissions to create files and folders in gap-4-10.1/pkg, can you try 
"sudo ./install.sh"?

**Comment by lmyreg2017** [comment]
Dear Kamal,

Attached is my output when I run ./install.sh or sudo ./install.sh, then I
realized that libtoolize is not installed, so I use

sudo apt-get install libtool

to get it installed. The second screenshot shows some new errors when
I run ./install.sh again.


Best,

Muyang

**Comment by kamalsaleh** [comment]
Sorry, I can not find the attachment you mentioned. It might be better to reply directly in github.

**Comment by lmyreg2017** [comment]
![Screenshot from 2019-10-16 22-23-29](https://user-images.githubusercontent.com/33969980/66993838-48e35a80-f09a-11e9-8bcb-96c2ebba12ee.png)


Sorry, I am not very familiar with GitHub, attached is the output when I load ./install.sh

**Comment by kamalsaleh** [comment]
Can you tell me what files are listed in `current_cddlib/build/include/`?
If everything went good while compiling, then you should find the following files: `cdd.h  cdd_f.h  cddmp.h  cddmp_f.h  cddtypes.h  cddtypes_f.h  setoper.h  splitmix64.h`, some of which seem to be missed in your case.

**Comment by lmyreg2017** [comment]
I have the following files in  current_cddlib/build/include/

cdd.h  cddmp.h  cddtypes.h  setoper.h  splitmix64.h

Yes, cdd_f.h, etc are missing in my directory.

**Comment by zickgraf** [comment]
I can reproduce this issue: probably the package `libgmp-dev` is missing.

@lmyreg2017: Could you run `sudo apt-get install libgmp-dev` and try again?

@kamalsaleh: Maybe you could add `libtool` and `libgmp-dev` to the README.

**Comment by kamalsaleh** [comment]
Thank you Fabian. I removed the libgmp-dev library to test whether I can reproduce the error, and it returns a very similar one, namely that gmp.h is missing. I believe this could really fix the issue.

**Comment by lmyreg2017** [comment]
Dear Fabian and Kamal,

Thanks a lot for the help, yes, libgmp-dev is what I missed for installing,
and now CddInterface can be compiled successfully.

Best,
Muyang
